services:
  tropicana-guide:
    build: .
    container_name: tropicana_guide_app
    ports:
      - "5000:5000"
    volumes:
      - .:/globetrotter
    environment:
      - FLASK_ENV=development
      - PORT=5000
    env_file:
      - .env