server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;
    }

    location /static/ {
        root /usr/share/nginx/html;
    }

    location /api/pois {
        proxy_pass http://locations-service:5001/api/pois;
        proxy_set_header Host $host;
    }

    location /api/assistant {
        proxy_pass http://assistant-service:5002/api/assistant;
        proxy_set_header Host $host;
    }

    location /api/auth {
        proxy_pass http://auth-service:5003/api/auth;
        proxy_set_header Host $host;
    }
}
